name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.2.4
  english_words: ^4.0.0
  provider: ^6.0.0
  chinese_font_library: ^1.2.0
  http: ^1.2.2
  intl: ^0.19.0
  emoji_picker_flutter: ^1.0.0
  path_provider: ^2.1.4
  file_picker: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/config.json
    - assets/images/default_user.jpg
  uses-material-design: true